title: Rob Knight
author:
  name: Rob Knight
  photoUrl: 'http://www.gravatar.com/avatar/217c7106a3d4eba3584cd38abf8ee107?s=128'
  twitterId: robknight_
  githubId: robertknight
  email: robertknight@gmail.com
